### ISSUE TITLE
json files getting replaced not merged

### ISSUE THREAD

**Issue by bentzibentz** [ngneat/transloco-keys-manager#1]
## I'm submitting a bug

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

First of all, thanks for this pretty cool translation tool. 

The extract command replaces all values at the generated language json files. In the documentation is written that replace default is false but it is not working.
If i set replace to false at the transloco.config.js by my self it is also not working and replaces all key values at the json files instead of merging them.

<code>
module.exports = {
  rootTranslationsPath: 'src/assets/i18n/',
  langs: ['de', 'en', 'es'],
  keysManager: {
    replace: false
  }
};
</code>

## Expected behavior

The extract command should only add new translations key to the json files and do not replace all values.

## Minimal reproduction of the problem with instructions

Set up new angular project install transloco and set up some translations, in my case with the structural directive.

## What is the motivation / use case for changing the behavior?

Extraction without merging the new keys into the json is pretty annoying

## Environment

<pre><code>
Angular version: 8.2.11
@ngneat/transloco: 2.5.2
@ngneat/transloco-keys-manager: 1.0.0

For Tooling issues:
- Node version: v12.3.1
- Platform:  macOs 10.15

Others:

</code></pre>

**Comment by shaharkazaz** [comment]
@bentzibentz Thanks for your report, we will look into it 👍

**Comment by NetanelBasal** [comment]
Do you mean with `transloco-keys-manager extract` command? Because it works fine.

**Comment by bentzibentz** [comment]
i tried both the cli command and the webpack plugin, it always replaces the whole json files and resets the values with something like: Missing value for 'xyz'

**Comment by NetanelBasal** [comment]
The only issue that I see is that it resets the values.

**Comment by bentzibentz** [comment]
Right, that's what I wanted to say, sorry if that wasn't clear. Is this the desired behavior? Cause if i add a new component or change something my whole translation values are lost.

**Comment by NetanelBasal** [comment]
No, I'm fixing it now. I will also add a `--sort` option.

**Comment by bentzibentz** [comment]
Thanks a lot! Can't wait to use transloco in my new project :thumbsup:
