### ISSUE TITLE
Feature: find keys in arguments of pipes

### ISSUE THREAD

**Issue by Serrulien** [ngneat/transloco-keys-manager#114]
### Is there an existing issue for this?

No
- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I frequently use the transloco pipe inside arguments of another pipe:
```
{{ var | pipe : ( 'key' | transloco ) }}
{{ var | pipe : ({ foo: 'key' | transloco }) | another }}
```
In v3.1.1, translation keys in pipes' args are not detected by the keys manager. I would like them to be detected.

### I would like to make a pull request for this feature

Yes 🚀

**Comment by shaharkazaz** [comment]
Waiting to see your PR for it 😉
