### ISSUE TITLE
Feature: Support Nx workspace.json version 2

### ISSUE THREAD

**Issue by evanfuture** [ngneat/transloco-keys-manager#116]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this a regression?

No

### Current behavior

When extracting, the lib tries to find the `projectBasePath` based on either angular.json or workspace.json configurations.  But when using the project.json format with workspace.json version 2, the workspace.json only contains a reference to the path to the project.json, and that file then contains the sourceRoot and projectType.

Essentially, when migrating to this new format, eg with `nx generate @nrwl/workspace:convert-to-nx-project --all`, the extract command fails.

### Expected behavior

Nx workspace version 2 with project specific configs is supported.

### Please provide a link to a minimal reproduction of the bug

Not sure how with this...

### Please provide the environment you discovered this bug in

```markdown
Transloco: 
Transloco Keys Manager:
Angular:
Node: 
Package Manager: 
OS:
```

### I would like to make a pull request for this bug

Yes 🚀

**Comment by EndyKaufman** [comment]
i want this feature :(

**Comment by shaharkazaz** [comment]
@EndyKaufman Once the comments are fixed I'll merge & release ASAP

**Comment by shaharkazaz** [comment]
@EndyKaufman Can you please verify v3.3.0?

**Comment by EndyKaufman** [comment]
i try

**Comment by EndyKaufman** [comment]
@shaharkazaz 
not work, example repo https://github.com/EndyKaufman/new-nx-with-transloco-keys-manager
![image](https://user-images.githubusercontent.com/4127109/150577365-be4f9cc3-a5ed-4f0a-b622-75571e869b89.png)

**Comment by shaharkazaz** [comment]
@EndyKaufman Found the issue, please check 3.3.1, add a test for this case as well 👍

**Comment by EndyKaufman** [comment]
cool!!!!!

extract work in this sample
![image](https://user-images.githubusercontent.com/4127109/150591413-72b28897-435d-49c5-b0e4-fb8b6b2bf4b2.png)

I don't use find but ran for test and got error
![image](https://user-images.githubusercontent.com/4127109/150591612-2b45041f-a288-40d9-9a81-f8f2b80bc354.png)

**Comment by shaharkazaz** [comment]
@EndyKaufman The issue is with your transloco config, the Translations path shouldn't be absolute, it's relative to the src.
Change it to `assets/i18n` and it will work

**Comment by EndyKaufman** [comment]
it is not about this fix

it is about bad deps

![image](https://user-images.githubusercontent.com/4127109/150655628-8ec7b13d-66fb-4c85-8fd1-23a75f5ad128.png)
