### ISSUE TITLE
 Error: Cannot find module 'fs-extra'

### ISSUE THREAD

**Issue by asiomido** [ngneat/transloco-keys-manager#13]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Without karma installed an error occurs when using i18n:extract, i18n:find or webpack plugin:
```
> [project name removed]@0.0.0 i18n:extract [project path removed]
> transloco-keys-manager extract

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'fs-extra'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> ([project path removed]\node_modules\@ngneat\transloco-keys-manager\keysBuilder\buildTranslationFile.js:1:201)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! neptune@0.0.0 i18n:extract: `transloco-keys-manager extract`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the neptune@0.0.0 i18n:extract script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\[user name removed]\AppData\Roaming\npm-cache\_logs\2019-12-17T10_40_24_697Z-debug.log
```

## Expected behavior

The tool should run without errors.

## Minimal reproduction of the problem with instructions

For bug reports please provide the _STEPS TO REPRODUCE_ and if possible a _MINIMAL DEMO_ of the problem, for that you could use our [stackblitz example](https://stackblitz.com/edit/transloco-example)

- create new Angular Project
- uninstall karma
- install transloco
- install transloco-keys-manager
- run any of the commands `npm start`, `npm run i18n:extract`, `npm run i18n:find`

## Environment

<pre><code>
Angular CLI: 8.3.20
Node: 10.16.3
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.20
@angular-devkit/build-angular     0.803.20
@angular-devkit/build-optimizer   0.803.20
@angular-devkit/build-webpack     0.803.20
@angular-devkit/core              8.3.20
@angular-devkit/schematics        8.3.20
@angular/cli                      8.3.20
@ngtools/webpack                  8.3.20
@schematics/angular               8.3.20
@schematics/update                0.803.20
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2

</code></pre>

This bug probabbly was probabbly not discoved until now, becuase angular installs karma by default, which installs fs-extra. We removed karma, form our project, because we do not use it.
The fs-extra devDependency needs to be moved to the runtime dependencies.

**Comment by shaharkazaz** [comment]
@asiomido  Fixed in v1.2.6
