### ISSUE TITLE
Extracting from scoped library behaves differently in templates and .ts files

### ISSUE THREAD

**Issue by andre-gois** [ngneat/transloco-keys-manager#15]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Running the extraction on a library `transloco-keys-manager extract --unflat -i src/lib` behaves differently in templates and .ts files:

In the template, using `{{'MY_LIBRARY.BUTTON' | transloco}}` writes to the file `projects/my-library/src/assets/i18n/my-library/en.json`.
<pre><code>
{
    "BUTTON": "Missing value for 'MY_LIBRARY.BUTTON'"
}
</code></pre>

In the .ts files, using `this.translationService.translate('MY_LIBRARY.BUTTON2')` writes to the file `projects/my-library/src/assets/i18n/en.json`.
<pre><code>
{
    "MY_LIBRARY": {
            "BUTTON2": "Missing value for 'MY_LIBRARY.BUTTON2'"
    }
}
</code></pre>

Note:
In the library's module `my-library.module.ts` I have defined a Scope:
<pre><code>
providers: [
    {
      provide: TRANSLOCO_SCOPE,
      useValue: { scope: 'my-library', alias: 'MY_LIBRARY' },
    },
    ...
],
</code></pre>
## Expected behavior

In both situation the translations should end up on the same file

## Environment

<pre><code>
Angular version: 8

Browser:
- [x ] Chrome (desktop) version 78
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.16 
- Platform:  Mac

</code></pre>

**Comment by NetanelBasal** [comment]
When using the `translate` method, you should pass the `scope` as the third parameter:

```ts
this.translationService.translate('BUTTON2', params, 'my-library')
```
