### ISSUE TITLE
Support multiple apps/libs in NX workspace

### ISSUE THREAD

**Issue by sidyes** [ngneat/transloco-keys-manager#17]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

At the moment it is only possible to set one app within the `rootTranslationsPath`. I am using NX with multiple apps and libs. 

## Expected behavior

It should be possible to have multiple root translation paths / to support multiple apps.

## Minimal reproduction of the problem with instructions

Create two projects within a NX workspace.

## What is the motivation / use case for changing the behavior?

Make it usable within NX.

**Comment by NetanelBasal** [comment]
Can you explain what do you mean by "to support multiple apps"?

**Comment by sidyes** [comment]
I thought that `rootTranslationsPath` represents the root path of the main translations and it is only possible to set one path.
I have the following structure in my mono repository:
```
| -- apps
  | -- firstApp
     | -- src
        | -- app
        | -- assets
           | -- i18n
  | -- secondApp
     | -- src
        | -- app
        | -- assets
           | -- i18n 
| -- libs
   | -- libA
      | -- src
         | -- lib
            | -- assets
| -- transloco.config.js
```

Is it possible to handle that case?

**Comment by NetanelBasal** [comment]
firstApp and secondApp are not related, right?

**Comment by sidyes** [comment]
No they are completely independent apps.

**Comment by NetanelBasal** [comment]
In that case, we should provide a `--config` flag where you can pass a different configuration file.

**Comment by NetanelBasal** [comment]
@shaharkazaz

**Comment by NetanelBasal** [comment]
For now, you can do it inline:

```json
{
  "secondApp:i18n:extract": "transloco-keys-manager extract --translation-path ..."
}
```

**Comment by sidyes** [comment]
Good point, I will do it like this for now.

**Comment by adgoncal** [comment]
It would also be nice to have support for `--project` and check `angular.json` for the given project.
For example:

```typescript
// transloco.config.ts
module.exports = {
  translationPath: 'assets/i18n'
};

// angular.json
{
 "projects": {
    "first-app": {
      "sourceRoot": "apps/first-app/src"
    }
  }
}
```

Then 
```
transloco-keys-manager extract --project first-app
```
would use `apps/first-app/src/assets/i18n` as the `rootTranslationPath`.

**Comment by shaharkazaz** [comment]
@adgoncal released in v1.3.0, LMK how it works for you.

**Comment by adgoncal** [comment]
@shaharkazaz thank you for implementing this feature! However, I am currently unable to test it because it is throwing an error:
```
TypeError: Cannot destructure property `sourceRoot` of 'undefined' or 'null'.
    at Object.resolveProjectPath (my-app/node_modules/@ngneat/transloco-keys-manager/helpers/resolveProjectPath.js:1:312)
    at Object.resolveConfig (my-app/node_modules/@ngneat/transloco-keys-manager/helpers/resolveConfig.js:1:446)
```

It looks like it was not able to find my angular configuration, which is located in `angular.json`.
https://github.com/ngneat/transloco-keys-manager/blob/000aff53006850ab24fcb663754371a3afe54335/src/helpers/resolveProjectPath.ts#L4


The documentation for `cosmiconfig` says by default it would look for the rc file in json format (ie: `.angularrc.json`), or the `.config.js` file (ie: `angular.config.js`). I think you will need a custom configuration in the second parameter in order to load from `angular.json`.

> By default, Cosmiconfig will start where you tell it to start and search up the directory tree for the following:
>
> - a package.json property
> - a JSON or YAML, extensionless "rc file"
> - an "rc file" with the extensions .json, .yaml, .yml, or .js.
> - a .config.js CommonJS module
>
> For example, if your module's name is "myapp", cosmiconfig will search up the directory tree for configuration in the following places:
>
> - a myapp property in package.json
> - a .myapprc file in JSON or YAML format
> - a .myapprc.json file
> - a .myapprc.yaml, .myapprc.yml, or .myapprc.js file
> - a myapp.config.js file exporting a JS object

**Comment by shaharkazaz** [comment]
@adgoncal Thanks again for the feedback, can you try 1.3.2? 🙂

**Comment by adgoncal** [comment]
> @adgoncal Thanks again for the feedback, can you try 1.3.2? 🙂

That is perfect! Thank you again!
