### ISSUE TITLE
Support Inline Loaders

### ISSUE THREAD

**Issue by vaceslav** [ngneat/transloco-keys-manager#2]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

When the project use [Inline Loaders](https://netbasal.gitbook.io/transloco/lazy-load-translation-files/inline-loaders) (a scope with loader), then I get error by find and extract commands. 

## Expected behavior

Finder should find keys in lazy loaded modules and extractor should extract keys in the correct folder.

## Environment

<pre><code>
Angular CLI: 8.3.14
Node: 12.3.1
OS: win32 x64
Angular: 8.2.12

 
- Platform:   Windows 

</code></pre>

**Comment by NetanelBasal** [comment]
We currently don't support inline loaders. It's on our road map.

**Comment by NetanelBasal** [comment]
v1.1.0:

https://github.com/ngneat/transloco-keys-manager/#inline-loaders
