### ISSUE TITLE
Keys detective run endlessly when pointing to specific i18n file

### ISSUE THREAD

**Issue by ronnetzer** [ngneat/transloco-keys-manager#21]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

When using --translations-path flag and pointing to a specific language file, the process runs endlessly in "Checking for missing keys" stage.

## Expected behavior

finish the process and show the summary, or don't allow pointing to a specific file and fail the process with some explanation.

## Minimal reproduction of the problem with instructions

run the command with --translations-path flag and point it to a specific json file

## Environment

<pre><code>
Angular version: 8.2.3
Keys Manager: 1.3.2
Node version: 10.13
Platform: Mac

</code></pre>

**Comment by shaharkazaz** [comment]
@ronnetzer translation path points to a directory, I will add a check and fail the process to prevent the loop.
