### ISSUE TITLE
Detective dosn't detect keys with parentesis simbols

### ISSUE THREAD

**Issue by luixolema** [ngneat/transloco-keys-manager#25]
valores proporcionados I'm submitting a...

<pre><code>
[ ] Regression
[x] Bug report
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other
</code></pre>

## Current behavior

When you run the i18n:extract comand the keys with parentesis simbols are not found

Firts than anything: cngratulations on your excelet work

It may be not the best practice to choose words based keys approach, but in this case the manager doen't detect the keys with "(",")" simbols.

PD: sorry if my inglish it's not so good.
## Environment
Angular version: 7.2.0

For Tooling issues:
- Node version: 10.18.0
- Platform: Linux

**Comment by NetanelBasal** [comment]
Add an example, please.

**Comment by shaharkazaz** [comment]
@luixolema can you please provide an example? 🙂

**Comment by shaharkazaz** [comment]
@luixolema reopen this with an example if still relevant, try using v2.0.0
