### ISSUE TITLE
Support for nested objects

### ISSUE THREAD

**Issue by vaceslav** [ngneat/transloco-keys-manager#3]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

HTML  file
<pre><code>
<span>{{'todos.title1' | transloco}}</span>  
<span>{{'todos.title2' | transloco}}</span>
</code></pre>

then run **transloco-keys-manager extract**
It generates following json:
<pre><code>
{
  "todos.title1": "Missing value for 'todos.title1'",
  "todos.title2": "Missing value for 'todos.title2'",
}
</code></pre>

## Expected behavior

It should generate  nested JSON file, like this one:
<pre><code>
{
  "todos" : {
    "title1": "Missing value for 'todos.title1'",
    "title2": "Missing value for 'todos.title2'"
  }
}
</code></pre>

## Environment

<pre><code>

Angular CLI: 8.3.14
Node: 12.3.1
OS: win32 x64
Angular: 8.2.12

</code></pre>

**Comment by NetanelBasal** [comment]
It's by design.

**Comment by NetanelBasal** [comment]
We'll consider adding a flat in the next release.

**Comment by NetanelBasal** [comment]
v1.1.0: 

```
transloco-keys-manager extract --unflat
transloco-keys-manager extract -u
```
