### ISSUE TITLE
Empty defaultValue not respected when extracting keys

### ISSUE THREAD

**Issue by MikeDabrowski** [ngneat/transloco-keys-manager#31]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I wanted to have empty missing translation values so I passed `-d ""`  to extract command. It was ignored - the default fell back to 'Missing value for...'. 

## Expected behavior

I'd expect empty defaultValue to be respected

## Minimal reproduction of the problem with instructions

`"i18n:extract": "transloco-keys-manager extract -u -l en de fr -d \"\"",`

## What is the motivation / use case for changing the behavior?

In our project we use BabelEdit to help translating the strings. BabelEdit detects empty strings and allows easy 'one-click' machine translation for all empty keys.

## Environment

every

## Possible bug location

https://github.com/ngneat/transloco-keys-manager/blob/060382f0ae479ccaae8b3608dc946185e1e6df35/src/keysBuilder/addKey.ts#L12-L14

**Comment by shaharkazaz** [comment]
@MikeDabrowski fixed in v2.0.5 🙂
