### ISSUE TITLE
Deep sorting of keys extractor result

### ISSUE THREAD

**Issue by bpiasecki** [ngneat/transloco-keys-manager#33]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

After extracting keys by webpack plugin only first level keys are sorted in JSON file:

```
JSON:
{
    "login": {
        "password": "password",
        "sign in": "sign in"
        },
    "user": {
        "profile": "profile",
        "image": "image"
        }
}

```
## Expected behavior

Deep sorting of second level keys - 'profile' and 'image' shoud be sorted as well as 'login' and 'user'
```
HTML:
<ng-container *transloco="let t; read: 'user'">
    <span>{{ t('image') }}</span>
    <span>{{ t('profile') }}</span>
</ng-container>

JSON:
{
    "login": {
        "password": "password",
        "sign in": "sign in"
        },
    "user": {
        "image": "image",
        "profile": "profile"
        }
}
```

## Minimal reproduction of the problem with instructions

Starting app with `--extra-webpack-config webpack-dev.config.js`, then keys extractor generates keys which are sorted only on first level, nested keys are not sorted. This behavior causes merging problems, because nested keys are generated every time in different order.

## Environment

<pre><code>
Angular version: 8.2.3

For Tooling issues:
- Node version: v12.16.3
- Platform:  Windows 10

Others:
webpack-dev.config.js:
module.exports = {
  plugins: [new TranslocoExtractKeysWebpackPlugin({
    defaultValue: "{{key}}",
    langs: ["en"],
    unflat: true,
	sort: true
  })]
};
</code></pre>

**Comment by shaharkazaz** [comment]
@bpiasecki Seems to work as expected with both your example and I added some keys in random order and they were sorted alphabetically.
Can you add a reproduction repo so I can further investigate?

**Comment by bpiasecki** [comment]
@shaharkazaz Did you set 'unflat' option to true in webpack config file? Because i think that it might be a problem. Everything is sorted when this option is set to false.

**Comment by shaharkazaz** [comment]
@bpiasecki yes I did, if you don't use it there is no depth 😄 
I tried several times and it seemed to work, try to create a small reproduction so I can check your use case.

**Comment by bpiasecki** [comment]
@shaharkazaz I updated keys-manager version and now everything works fine, thanks for help 😄
