### ISSUE TITLE
Keys Detective's return code for automated validation

### ISSUE THREAD

**Issue by JerryDoubleU** [ngneat/transloco-keys-manager#34]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

`transloco-keys-manager find` always ends with code 0 (no error).

## Expected behavior

It would be useful if the `transloco-keys-manager find` would return some different exit code if _missing keys_ would be found. This would enable to use this tool for validation in build/release tools like CI.

## Minimal reproduction of the problem with instructions

Run the `transloco-keys-manager find` and see the exit code.

## What is the motivation / use case for changing the behavior?

I would like to automate the process and make it easy for the developers and the CI to notice that some keys are missing (and not translated) in the extracted file.

## Environment
For Tooling issues:
- Node version: v12.16.2
- Platform:  Windows

**Comment by shaharkazaz** [comment]
@JerryDoubleU I can see that in case you have missing keys and the `addMissingKeys` option is disabled the process will [exit with code 1](https://github.com/ngneat/transloco-keys-manager/blob/master/src/keysDetective/buildTable.ts#L60).
What other cases are you referring to?

**Comment by JerryDoubleU** [comment]
That sounds like it, thanks!
It'd also be useful to be able to get the info about the 'extra keys' (exit code 2?) to be aware of the extra keys which are no longer used, or have been mistyped.

**Comment by shaharkazaz** [comment]
would you like to make a PR for it? 🙂

**Comment by JerryDoubleU** [comment]
Definitely! I'll do this this week.

**Comment by shaharkazaz** [comment]
@JerryDoubleU available in v2.1.0. Great work!
