### ISSUE TITLE
Translations path error since release 2.x.x 'Translations path path provided doesn't exist!'

### ISSUE THREAD

**Issue by TomWieschalla** [ngneat/transloco-keys-manager#36]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

node script 
`transloco-keys-manager find --translations-path src/assets/i18n/ --langs de`
 throws 
`Translations path path provided doesn't exists!`

## Expected behavior

1. translations path is given -> no error
2. should show missing keys on console and return error code [1]
3. error should show the inserted path to the developer

## Minimal reproduction of the problem with instructions

package.json
```
{
 "scripts": {
 "i18n:find": "transloco-keys-manager find --translations-path src/assets/i18n/ --langs de" 
 }
}
```

project structure
📜package.json
 ┗ 📂src
 ┃ ┣ 📂assets
 ┃ ┃ ┗ 📂i18n
 ┃ ┃ ┃ ┗ 📜de.json

_STEPS TO REPRODUCE_
1. Update transloco-keys-manager from 1.3.2 -> 2.X.X 
2. run on console:
`$npm run i18n:find`

## What is the motivation / use case for changing the behavior?

To include the 'i18n:find' script into our ci pipeline for missing key detection.

## Environment

<pre><code>
Angular version:
Angular v9.1.5
 
For Tooling issues:
- Node version: v12.16.2
- Platform:  MacOS v10.14.6

Others:
Transloco v2.17.1
Transloco-keys-manager v2.0.6
</code></pre>

**Comment by shaharkazaz** [comment]
@TomWieschalla change `src/assets/i18n/` to `assets/i18n/`.
The `sourceRoot` property is prefixing the paths, and if you don't provide a target project or the `angular.json` file is missing, a default `src` is used.

**Comment by TomWieschalla** [comment]
@shaharkazaz thanks, runs

**Comment by Anatolie-Pesterean** [comment]
This plugin works fine for regular Angular apps.

But when I trying to use it in monorepo (NX), where angular.json does not exist, this default "src" value that you introduced just ruins everything.

How can I configure it for NX monorepo?

**Comment by Anatolie-Pesterean** [comment]
This plugin works fine for regular Angular apps.

But when I trying to use it in monorepo (NX), where angular.json does not exist, this default "src" value that you introduced just ruins everything.

How can I configure it for NX monorepo?

**Comment by AbdealiLoKo** [comment]
I had this same issue and removing my "src" fixed the issue.
But I am unclear on what is the expected behavior here.

I reproduced the issue at: https://stackblitz.com/edit/node-angular-transloco
`extract` works - but `find` does not work
Here I run: 
```
$ npm install
...
added 1001 packages, and audited 1002 packages in 46s

$ ./node_modules/.bin/transloco-keys-manager extract

Starting Translation Files Build 👷🏗

✔ Extracting Template and Component Keys 🗝
ℹ 3 keys were found in 5 files.

              🌵 Done! 🌵

$ ./node_modules/.bin/transloco-keys-manager find
Translations path provided doesn't exists!

$ ./node_modules/.bin/transloco-keys-manager find --translations-path assets/i18n/

 🕵 🔎  Starting Search For Missing Keys 🔍 🕵

✔ Extracting Template and Component Keys 🗝
✔ Checking for missing keys ✨
✔ Summary

┌───────────┬──────────────┬──────────────────────────────────────────┐
│ File Name │ Missing Keys │ Extra Keys                               │
├───────────┼──────────────┼──────────────────────────────────────────┤
│ en        │ --           │ 'angular'                                │
├───────────┼──────────────┼──────────────────────────────────────────┤
│ zh        │ --           │ 'Angular'                                │
│           │              │ 'Hello'                                  │
│           │              │ 'Start editing to see some magic happen' │
│           │              │ 'angular'                                │
└───────────┴──────────────┴──────────────────────────────────────────┘
```

Is it right that extract works fine but find does not work fine ? They both seem to be using different projectRoot ?
