### ISSUE TITLE
Add support for Angular libraries to Keys Detective

### ISSUE THREAD

**Issue by potray** [ngneat/transloco-keys-manager#40]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Angular's suggested folder structure is the following:

- Root
  - node_modules
  - projects
    - lib1
    - lib2
  - src
    - app
    - assets

It's very common to need translation support in files inside the libraries. In our case, we have one unique file per language for all libraries and app inside the `assets` folder. 

There's no problem with the keys extractor, but our problem is with the keys detective, since:
- Running it with `-i src` will detect keys existing in `projects` as extra keys.
- Running it with `-i projects` will detect keys existing in `src/app` as extra keys.
- Running it with `-i .` will scan `node_modules` which is less than ideal and causes errors.

## Expected behavior

We think either one of the following functionalities will solve the problem:
- Add an option to exclude one or several folders, so folders like `node_modules` aren't scanned.
- Add the option for adding multiple inputs folder.

## Minimal reproduction of the problem with instructions

- Create a new project using Angular CLI.
- Add a new library using Angular CLI.
- Add some translation keys in both the library and the `app` folder.
- Try to use the Keys Detective.

## What is the motivation / use case for changing the behavior?

Having the need for translation support in both an Angular application and libraries at the same time.

**Comment by shaharkazaz** [comment]
@potray just to make sure I understand, you also have keys in your src folder? the src contains your main app and projects you supporting libs??

**Comment by potray** [comment]
@shaharkazaz Yes, we have keys in both `root/projects/` and in `root/src/app/`. Sadly scanning in `root` also scans `node_modules`, so it's not an option.

**Comment by shaharkazaz** [comment]
@potray How about we add support for an array of input paths? 
Would you like to create a PR for it?

**Comment by potray** [comment]
@shaharkazaz That would be perfect.

I cannot promise a PR since lately I'm having difficulties finding time to do stuff, but if I can and nobody is on it I can try :)

**Comment by shaharkazaz** [comment]
@potray try v2.2.0 and LMK how it goes 🙂

**Comment by potray** [comment]
Thanks for the new functionality! I updated but sadly I'm experiencing the following

```
/home/yarrick/bee/client/node_modules/@ngneat/transloco-keys-manager/helpers/updateScopesMap.js:1
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});const toCamelCase_1=require("./toCamelCase"),readFile_1=require("./readFile"),glob=require("glob"),scopes_1=
require("../keysBuilder/scopes"),tsquery_1=require("@phenomnomnominal/tsquery"),base="ObjectLiteralExpression:has(PropertyAssignment > Identifier[name=TRANSLOCO_SCOPE]) Propert
yAssignment:has(Identifier[name=/useValue|useFactory/])",useStringQuery=`${base} > StringLiteral`,useObjectQuery=`${base} > ObjectLiteralExpression`;function updateScopesMap({i
nput:e,files:s}){const t=s||e.map(e=>glob.sync(`${e}/**/*.ts`)).flat(),r={};for(const e of t){const s=readFile_1.readFile(e);if(!1===s.includes("TRANSLOCO_SCOPE"))continue;let
t={};const o=tsquery_1.tsquery.ast(s),i=tsquery_1.tsquery(o,useStringQuery);if(0===i.length){const e=tsquery_1.tsquery(o,useObjectQuery);for(const s of e)for(const e of s.prope
rties)if(e.initializer){const s=e.name.text;

TypeError: e.map(...).flat is not a function
    at Object.updateScopesMap (/home/yarrick/bee/client/node_modules/@ngneat/transloco-keys-manager/helpers/updateScopesMap.js:1:593)
    at Object.resolveConfig (/home/yarrick/bee/client/node_modules/@ngneat/transloco-keys-manager/helpers/resolveConfig.js:1:1099)
    at Object.findMissingKeys (/home/yarrick/bee/client/node_modules/@ngneat/transloco-keys-manager/keysDetective.js:1:491)
    at Object.<anonymous> (/home/yarrick/bee/client/node_modules/@ngneat/transloco-keys-manager/index.js:2:832)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
```

Sadly before I updated to v2.2.0 I was using v2.1.0 without trying the `find` script, and before that we were using v1 (yes, we totally forgot to update it for very long 😅) so I cannot provide further information.

**Comment by shaharkazaz** [comment]
@potray can you please provide more information? node version, the configuration used, and every env related info.

**Comment by potray** [comment]
Sure:

- npm v6.14.4
- node v10.21.0
- The script I ran: `transloco-keys-manager extract --unflat --sort`
- Environment (all running inside a WSL 2 instance):
  - Distributor ID: Ubuntu
  - Description:    Ubuntu 20.04 LTS
  - Release:        20.04
  - Codename:       focal

Anything else that could be useful?

**Comment by shaharkazaz** [comment]
@potray The issue is with your node version, array flat is supported starting Node 11.
I'll add a polyfill and release a fix.

**Comment by shaharkazaz** [comment]
@potray can you please try v2.2.1?

**Comment by potray** [comment]
@shaharkazaz works like a charm!!

**Comment by shaharkazaz** [comment]
@potray I need you to isolate the issue.
Please try each input path alone and see which one reproduces this error.
Also, try to downgrade back to 2.1.0 and re-run on each path.
Thanks

**Comment by potray** [comment]
@shaharkazaz I was able to isolate the issue.

We have a file with the following content:
```typescript
//noinspection ES6UnusedImports
import {} from '@ngneat/transloco'; // for key extractor to work

/**
 * t(action.collection.bigImpact)
 * t(action.collection.quickWins)
 * t(action.collection.triedAndTested)
 * t(action.collection.groundwork)
 * t(action.collection.allActions)
 */
```

Somehow removing one of the lines makes the error disappear. This is very weird and it makes little sense to me, but it's what I experience 😕

**Comment by shaharkazaz** [comment]
@potray which line are you removing?
And why do you have such a file? Shouldn't it be part of the template or an actual component file?

**Comment by potray** [comment]
@shaharkazaz Removing any of the 5 lines in the comment make the script work.

We have more content in that file (models to be more exact), but I removed everything until I managed to find the culprit code, which is that comment.

**Comment by shaharkazaz** [comment]
@potray you say the first run works as expected? Re-runing triggers the error?
Have you tried to combine all the comment values under a single `t(...)`?

**Comment by potray** [comment]
@shaharkazaz Sorry, that was very misleading on my part. What happened exactly was the script ran, I identified extra keys because the comment was missing, I added the comment I wrote, and after that, the script failed.

If you mean combining them like this
```
/**
 * t(action.collection.bigImpact,action.collection.quickWins,action.collection.triedAndTested,action.collection.groundwork,action.collection.allActions)
 */
```

It also produces the same error.

**Comment by shaharkazaz** [comment]
@potray thanks for clarifying.
I'll try to reproduce but if you can provide a reproduction that would be great 👍

**Comment by potray** [comment]
@shaharkazaz Alright, this is crazy, but this is what happened:

I tried to recreate the issue in another Angular project and I was unable, so I thought something is wrong with our `en.json` file. I couldn't find anything so out of frustration I deleted the entire content of the `en.json` file, I still got the error, I undid, and now the error is gone 🤯 

I can only bet of an extraneous character somewhere in the file, but so far I've run both the `extract` and `find` scripts, and both work flawlessly in the two folders we needed.

Thanks a lot for your time!!

**Comment by shaharkazaz** [comment]
@potray glad to hear! If you ever do find the reason, do share :)
