### ISSUE TITLE
Throw error on missing keys

### ISSUE THREAD

**Issue by Wycza** [ngneat/transloco-keys-manager#44]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

There is an option to emit an error on extra keys but no for missing keys.

## Expected behavior

It would be useful if the transloco-keys-manager find would return exit code if missing keys would be found. This would enable to use this tool for validation in build/release tools like CI.

## Minimal reproduction of the problem with instructions

Missing option so there is no possibility to reproduce it

## What is the motivation / use case for changing the behavior?

I wouldn't like to push code with any missing keys.

## Environment

For Tooling issues:
- Node version: 12.18.1
- Platform: Windows 10

**Comment by Wycza** [comment]
I have all needed code changes already but I have a problem with pushing them. I don't know how to run tests. `npm run test` does not work for me.

`"test": "PRODUCTION=true jest",` = '_PRODUCTION' is not recognized as an internal or external command,_

`"test": "jest",` = _TypeError: string.replace is not a function_

Can you help me with running those tests?

**Comment by shaharkazaz** [comment]
@Wycza missing keys emits an error, the process will exit with exit code 1.

**Comment by Wycza** [comment]
@shaharkazaz ach yes. My bad. When I run ` ng g @ngneat/transloco:keys-manager` then version 1.0.0 was installed which didn't exit on missing keys. Then I updated it to the latest version but I was more focused on ` --emit-error-on-extra-keys` option instead of checking if it exit on missing keys. In this case we can close the issue. Thanks for quick reply 👍
