### ISSUE TITLE
po file support

### ISSUE THREAD

**Issue by zzakir** [ngneat/transloco-keys-manager#45]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

Is there an option to extract the keys into po files instead of a json file?

**Comment by shaharkazaz** [comment]
@zzakir would you like to make a PR for it? 🙂

**Comment by zzakir** [comment]
@shaharkazaz Sure! I will give it a shot.

**Comment by shaharkazaz** [comment]
@zzakir any update on that? 🙂

**Comment by zzakir** [comment]
@shaharkazaz Sorry about not updating you. Po file support was really important for my company and because of that they've decided to stick with ngx-translate for now. Because of my busy schedule I did not really get the time to look into this as well.

**Comment by shaharkazaz** [comment]
@zzakir I see, good luck anyways, hope to see you as a contributor here 😊

**Comment by orestisioakeimidis** [comment]
@shaharkazaz I made a PR (https://github.com/ngneat/transloco-keys-manager/pull/124) for it. Make sure to have a look. Thanks!
