### ISSUE TITLE
Wrong JSON format with Webpack plugin

### ISSUE THREAD

**Issue by zuehlkefagu** [ngneat/transloco-keys-manager#46]
Hi guys

We are using Transloco with the Webpack Plugin (thanks for that!) for extracting keys during development in combination with  dynamic keys.

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

As you can see we have a different output format of the json file. This only happens during development with the Webpack plugin, a manual run with transloco-keys-manager extract works as expected for both languages.

**Output**
de.json (As expected)
`
  "security": {
    "error": {
      "1": "xxxx",
      "2": "xxxx",
      "3": "xxx"
      ......
     }
   }
`

en.json (Wrong)
`
  "security": {
    "error": [
      null,
      "Missing value for 'security.error.1'",
      "Missing value for 'security.error.2'"
    ]
}
`

## Expected behavior

Same format for both language - like de.json

## Minimal reproduction of the problem with instructions

**Setup**
Dynamic keys definition inside *.ts
`
    /**
     * t(security.error.wrong-credentials, security.error.no-connection, security.error.old-app-version,
     * security.error.1, security.error.2, security.error.3, security.error.4, security.error.5, security.error.6,
     * security.error.7, security.error.8, security.error.9, security.error.10, security.error.11, security.error.12,
     * security.error.13, security.error.14, security.error.15, security.error.16, security.error.17, security.error.18,
     * security.error.19, security.error.20, security.error.21, security.error.22, security.error.23, security.error.24,
     * security.error.25, security.error.26, security.error.27, security.error.28, security.error.29, security.error.30,
     * security.error.31, security.error.32, security.error.33, security.error.34, security.error.35, security.error.36,
     * security.error.37, security.error.38, security.error.39, security.error.40, security.error.41, security.error.42,
     * security.error.43)
     */
`

transloco.config.js:
`
module.exports = {
  rootTranslationsPath: 'assets/i18n/',
  langs: ['de', 'en'],
  keysManager: {
    emitErrorOnExtraKeys: true,
    unflat: true,
  },
};
`

extra-webpack.config.ts contains
` config.plugins.push(new TranslocoExtractKeysWebpackPlugin({}));`

## What is the motivation / use case for changing the behavior?

Using Transloco during development with automated key extraction.

## Environment

<pre><code>
Angular version: 9.1.11
 
For Tooling issues:
- Node version: 12.5.0
- Platform:  Windows
</code></pre>

**Comment by shaharkazaz** [comment]
@zuehlkefagu can you please provide a small reproduction repo so I can better test it? 🙂

**Comment by shaharkazaz** [comment]
@zuehlkefagu should be fixed in v2.4.2
