### ISSUE TITLE
"transloco-keys-manager find" support for dynamically created strings(keys) in html

### ISSUE THREAD

**Issue by stsglnt** [ngneat/transloco-keys-manager#49]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Dynamicly generated translation strings (for example <p>{{t(dynamicKey + '.title')}}) is not recognized by key-manager and  "transloco-keys-manager find" sees those strings (inside i18n json files) as an extra ones. So In my app I have json structured like that: 
{
  "instagram": {"title": "Instram Title"},
  "facebook":  {"title": "Facebook Title"}
}

## Expected behavior

Would be nice if there was a possibility either to suppress specific strings (keys) for key-manager or somehow make it see that they are actually used. 

## Minimal reproduction of the problem with instructions
Here is an example of such structure. (Unfortunately I don't how if it's possible to run key-manager somehow in stackblitz)
https://stackblitz.com/edit/ngneat-transloco-i1jga7

## What is the motivation / use case for changing the behavior?
I use "transloco-keys-manager find -e"  (so it throws an error) and thus it blocks my pipelines(CI) steps. I would like to keep this behivor but still be able to use dynamic keys.
## Environment

<pre><code>
Angular version: 9.1.11

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v14.2.0

- Platform:   Linux

Others:

</code></pre>

**Comment by shaharkazaz** [comment]
@stsglnt have you seen the [dynamic keys section](https://github.com/ngneat/transloco-keys-manager#dynamic-keys) in the docs?

**Comment by stsglnt** [comment]
Oh... this is totally my bad. I have not understood that part at first. Now I see. Thanks for an unbelievably fast response.
