### ISSUE TITLE
duplicated keys extracted for scoped translations

### ISSUE THREAD

**Issue by stefanomiccoli** [ngneat/transloco-keys-manager#50]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Specifying comments for scoped dynamic keys results in keys added to both the scope translation file and the global file, with wrong and cluttering keys in global file

## Expected behavior

keys are only included in `i18n/library/en.json` with the scope (library)+key(style.one) structure as `library.style.one`

## Minimal reproduction of the problem with instructions
1. I have defined a scope in my lazy loaded module routes as follow:
```
@NgModule({
  imports: [RouterModule.forChild(routes)],
  providers: [{ provide: TRANSLOCO_SCOPE, useValue: 'library' }],
  exports: [RouterModule]
})
export class LibraryRoutingModule { }
```

2. I init the directive in templates adding comments for the dynamic keys as follow:
```
<div class="group-tags" *transloco="let t; read: 'library'">
        <!-- t(style.one, style.two, style.three) -->
</div>
```

3. I run the `transloco-keys-manager extract` script

4. I get keys included in `i18n/library/en.json`
```
[...]
"style": {
    "one": "Missing value for 'library.style.one'",
    "two": "Missing value for 'library.style.two'",
    "three": "Missing value for 'library.style.three'"
  },
[...]
```
**and**  in `i18n/en.json`
```
  "style": {
    "one": "Missing value for 'style.one'",
    "two": "Missing value for 'style.two'",
    "three": "Missing value for 'style.three'"
  }
```

## Environment

<pre><code>
Angular version: 10.0.3
Transloco version: 2.17.4
Transloco keys manager version: 2.2.1
</code></pre>

**Comment by stefanomiccoli** [comment]
just realized there's actually no connection between the scope and the duplicate keys, by coincidence, the read value from yesterday example matched with our scope. but even in a simpler scenario, very close to the docs, like the following

```
<ng-container *transloco="let m; read: 'messages'">
  <!-- t(tag1, tag2) -->
</ng-container>
```

i got duplicates in en.json (flattened or unflattened doesnt make a difference)
```
  [...],
  "messages.tag1": "Missing value for 'messages.tag1'",
  "messages.tag2": "Missing value for 'messages.tag2'",
  "tag1": "Missing value for 'tag1'",
  "tag2": "Missing value for 'tag2'",
  [...]
```

**Comment by shaharkazaz** [comment]
@stefanomiccoli can you please provide a small reproduction repo? 🙂

**Comment by melonparfait** [comment]
I'm also encountering this exact same behavior. I created a reproduction at https://github.com/melonparfait/transloco-extract-duplicate-keys

**Comment by shaharkazaz** [comment]
@melonparfait I'll take a look, thanks 🙂

**Comment by Alegiter** [comment]
Any progress on this issue?
Realy need to be fixed

**Comment by shaharkazaz** [comment]
@Alegiter There is no timeline for it since I need to find the time to test and make the fix 🙂 
You are more than welcome to create a PR for it.
I hope I will get to it this weekend (I'm a college student so I had a lot of stuff going on lately )

**Comment by Alegiter** [comment]
Found workaround. Strange, but it works for me.

If I move comment with key out of *transloco container. 
And add "readValue" to key, then extract works as expected - puts key only in scope folder. No duplicates

Before:
```
<ng-container *transloco="let t; read: 'readValue'">
<!--t(key)-->
```

After:
```
<!--t(readValue.key)-->
<ng-container *transloco="let t; read: 'readValue'">
```

**Comment by Alegiter** [comment]
Trying to reproduce my [previous answer](https://github.com/ngneat/transloco-keys-manager/issues/50#issuecomment-685739065) in new ng project.

My answer is not works
And current issue don`t reproduced

Magic :)

**Comment by shaharkazaz** [comment]
@melonparfait
Tested on the reproduction you provided.
Can all of you please test v2.3.1? 🙂

**Comment by Alegiter** [comment]
@shaharkazaz 
Bug fixed for me
Thank you :)

**Comment by ttan-beckman** [comment]
Fixed for me too. Thanks!

**Comment by melonparfait** [comment]
Fixed for me too. Thanks!

**Comment by mkubdev** [comment]
I have the same bug. I'm on angular12 and transloco 2.22.0 !

My template :
```html
<ng-container *transloco="let t; read :'search'">
  <input class="input_text" #searchBox [placeholder]="t('placeholder')" (input)="search(searchBox.value)">
  <p>{{ t('cta_text') }}</p>
</ng-container>
```
My translation file `en.json` :
```json
"search": {
  "placeholder": "This is a placeholder",
  "cta_text": "I'm a cta text"
}
```
  
I run `npm run i18n:extract` and i get the following result :
  
  ```json
"search.placeholder": "Missing key",
"search.cta_text": "Missing key",  
"search": {
  "placeholder": "This is a placeholder",
  "cta_text": "I'm a cta text"
}
```
