### ISSUE TITLE
Sort keys and their comments for translators together

### ISSUE THREAD

**Issue by brlx** [ngneat/transloco-keys-manager#53]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

When using [comments for translators](https://ngneat.github.io/transloco/docs/tools/comments), and then the key extractor (ie. `transloco-keys-manager extract`), the extractor reorders the json files, and moves the comments away from the key they are explaining.

So the following original json (some parts omitted)
```json
{
    "form.comment": "Form field names/labels, which are in front of the inputs",
    "form": {
        "name": {
            "label": "Name"
        }
    },
    "otherStuff": {
        "other": "stuff"
    }
}
```

when the extractor adds new keys to sections which are omitted in the example, becomes the following
```json
{
    "form": {
        "name": {
            "label": "Name"
        }
    },
    "otherStuff": {
        "other": "stuff"
    },
    "form.comment": "Form field names/labels, which are in front of the inputs"
}
```
Notice how `form.comment` was moved down, which makes it hard to spot if the key has a comment, because there might be a ton of lines between the comment and the actual key.

## Requested behavior

Comments should be sorted together with their keys. Maybe the comments should be sorted _before_ the keys, because in case when the comment is for a whole block, that is more readable, se the original example above.

## Minimal reproduction of the problem with instructions

1. Create some keys in templates, then have them extracted into the language files with `transloco-keys-manager extract`
1. Add comments to some keys or blocks, see the examples above.
1. Add some more keys in templates, then extract them with the same method
1. => comments are sorted away from their keys

### Our transloco config

`package.json`
```json
{
  "scripts": {
    "i18n:extract": "transloco-keys-manager extract --project <project-in-the-angular-workspace>"
  }
}
```

`transloco.config.js`
```javascript
module.exports = {
	rootTranslationsPath: 'projects/<project-in-the-angular-workspace>/src/assets/i18n/',
	langs: ['en', 'de', 'fr', 'it'],
	keysManager: {
		input: 'app',
		output: 'assets/i18n',
		defaultValue: '[-]{{key}}',
		unflat: true,
	},
};

```

## What is the motivation / use case for changing the behavior?

We hand out the whole language files directly to translators, ie. we don't have any further mechanism to extract the not-yet-translated keys. They know how to search for the missing indicators and fill the translations in, but they have to search to check if a certain key has a comment, because they are sorted away.

## Environment

I don't think the angular version is relevant, but just to be on the safe side, here are the deps:
```
    ...
    "@angular/animations": "~8.2.4",
    "@angular/cdk": "~8.2.3",
    "@angular/common": "~8.2.4",
    "@angular/compiler": "~8.2.4",
    "@angular/core": "~8.2.4",
    "@angular/forms": "~8.2.4",
    "@angular/material": "~8.2.3",
    "@angular/platform-browser": "~8.2.4",
    "@angular/platform-browser-dynamic": "~8.2.4",
    "@angular/router": "~8.2.4",
    "@ngneat/transloco": "^2.13.3",
    "@ngneat/transloco-locale": "^1.1.1",
    ...
```
and the dev deps:
```
    ...
    "@ngneat/transloco-keys-manager": "^2.2.1",
    "@ngneat/transloco-optimize": "^1.0.1",
    ...
``` 

For Tooling issues:
- Node version: v10.16.3
- Platform: MacOS 10.15.5 (19F101)

**Comment by shaharkazaz** [comment]
@brlx Can you please share your configuration? are you using the sort option?

**Comment by brlx** [comment]
@shaharkazaz Thanks for the reply, added the section _Our transloco config_ above in the OP. Nothing else comes into my mind that I think would be relevant. So no, we don't use the `sort` option, and the default setting is `false`, if I am correct.

**Comment by shaharkazaz** [comment]
@brlx Have you tried running with the sort option set to `true`? 🙂  I think it might put those keys togther.

**Comment by brlx** [comment]
@shaharkazaz  well, this is lame and embarrassing, I have not found that earlier, even though I _swear_ that I read the docs multiple times.
Where do I send you (and/or the ngneat team) a beer for your work? Actually I wanted to do that earlier already, before coming with a specific question, but didn't find the button for that either.
