### ISSUE TITLE
Feature: Add support for function marker (not in a comment)

### ISSUE THREAD

**Issue by EndyKaufman** [ngneat/transloco-keys-manager#59]
In ngx-translate world exists key extractor https://github.com/biesbjerg/ngx-translate-extract#marker-function, this marker work in ts files

Example of DTO:
```typescript
import { _ } from 'any import with _ function';

class SignInDto {
    static titles = {
        username: _('Username'),
        password: _('Password')
    };
    username: string;
    password: string;
}
```
Example use in a component:
```typescript
@Component({
})
export class SignInComponent {
    titles = SignInDto.titles;
}
```
Example use in a template:
```html
<input matInput formControlName="username" [placeholder]="titles.username | transloco" />
<input matInput formControlName="password" [placeholder]="titles.password | transloco" />
```

i try will use import { translate } from '@ngneat/transloco'; but this function not for this, it force translate, it not for current case

now I use stupid code as a workaround this problem
```typescript
import { translate } from '@ngneat/transloco';

class SignInDto {
    static titles = {
        // tslint:disable-next-line: binary-expression-operand-order
        username: 'Username' || translate('Username'),
        // tslint:disable-next-line: binary-expression-operand-order
        password: 'Password' || translate('Password')
    };
    username: string;
    password: string;
}
```
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Minimal reproduction of the problem with instructions

For bug reports please provide the _STEPS TO REPRODUCE_ and if possible a _MINIMAL DEMO_ of the problem, for that you could use our [stackblitz example](https://stackblitz.com/edit/transloco-example)

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by EndyKaufman** [comment]
Example very stupid code for a workaround 
```typescript
import { translate } from '@ngneat/transloco';

export const USER_ENTITIES_STRINGS = {
    APPEND_GROUPS_TO_USER_TITLE: `Select groups for append to user` || translate(`Select groups for append to user`),
    DELETE_GROUPS_FROM_USER_TITLE: `Delete group` || translate(`Delete group`),
    DELETE_GROUPS_FROM_USER_MESSAGE: `Do you really want to delete group from user "{user.username}"?` || translate(`Do you really want to delete group from user "{user.username}"?`),
    SELECT_USER_TITLE: `Select user` || translate(`Select user`),
    SELECT_USERS_TITLE: `Select users` || translate(`Select users`),
    CREATE_USER_TITLE: `Create user` || translate(`Create user`),
    // tslint:disable-next-line: binary-expression-operand-order
    EDIT_USER_TITLE: 'Edit user #{id}' || translate('Edit user #{id}'),
    // tslint:disable-next-line: binary-expression-operand-order
    VIEW_USER_TITLE: 'User #{id}' || translate('User #{id}'),
    // tslint:disable-next-line: binary-expression-operand-order
    DELETE_USER_TITLE: 'Delete user #{id}' || translate('Delete user #{id}'),
    // tslint:disable-next-line: binary-expression-operand-order
    DELETE_USER_MESSAGE: 'Do you really want to delete user?' || translate('Do you really want to delete user?'),
};
```

**Comment by EndyKaufman** [comment]
@shaharkazaz please help me

**Comment by EndyKaufman** [comment]
Another big stupid code
```typescript
import { translate } from '@ngneat/transloco';

export const CORE_ENTITIES_STRINGS = {
    SELECT_CONTENT_TYPE_TITLE: `Select content type` || translate(`Select content type`),
    SELECT_CONTENT_TYPES_TITLE: `Select content types` || translate(`Select content types`),
    CREATE_CONTENT_TYPE_TITLE: `Create content type` || translate(`Create content type`),
    // tslint:disable-next-line: binary-expression-operand-order
    EDIT_CONTENT_TYPE_TITLE: 'Edit content type #{id}' || translate('Edit content type #{id}'),
    // tslint:disable-next-line: binary-expression-operand-order
    VIEW_CONTENT_TYPE_TITLE: 'Content type #{id}' || translate('Content type #{id}'),
    // tslint:disable-next-line: binary-expression-operand-order
    DELETE_CONTENT_TYPE_TITLE: 'Delete content type #{id}' || translate('Delete content type #{id}'),
    // tslint:disable-next-line: binary-expression-operand-order
    DELETE_CONTENT_TYPE_MESSAGE: 'Do you really want to delete content type?' || translate('Do you really want to delete content type?'),
    //
    APPEND_PERMISSIONS_TO_GROUP_TITLE: `Select permissions for append to group` || translate(`Select permissions for append to group`),
    DELETE_PERMISSIONS_FROM_GROUP_TITLE: `Delete permissions` || translate(`Delete permissions`),
    DELETE_PERMISSIONS_FROM_GROUP_MESSAGE: `Do you really want to delete permissions from group "{group.title}"?` || translate(`Do you really want to delete permissions from group "{group.title}"?`),
    SELECT_PERMISSION_TITLE: `Select permission` || translate(`Select permission`),
    SELECT_PERMISSIONS_TITLE: `Select permissions` || translate(`Select permissions`),
    CREATE_PERMISSION_TITLE: `Create permission` || translate(`Create permission`),
    // tslint:disable-next-line: binary-expression-operand-order
    EDIT_PERMISSION_TITLE: 'Edit permission #{id}' || translate('Edit permission #{id}'),
    // tslint:disable-next-line: binary-expression-operand-order
    VIEW_PERMISSION_TITLE: 'Permission #{id}' || translate('Permission #{id}'),
    // tslint:disable-next-line: binary-expression-operand-order
    DELETE_PERMISSION_TITLE: 'Delete permission #{id}' || translate('Delete permission #{id}'),
    // tslint:disable-next-line: binary-expression-operand-order
    DELETE_PERMISSION_MESSAGE: 'Do you really want to delete permission?' || translate('Do you really want to delete permission?'),
    //
    SELECT_GROUP_TITLE: `Select group` || translate(`Select group`),
    SELECT_GROUPS_TITLE: `Select groups` || translate(`Select groups`),
    CREATE_GROUP_TITLE: `Create group` || translate(`Create group`),
    // tslint:disable-next-line: binary-expression-operand-order
    EDIT_GROUP_TITLE: 'Edit group #{id}' || translate('Edit group #{id}'),
    // tslint:disable-next-line: binary-expression-operand-order
    VIEW_GROUP_TITLE: 'Group #{id}' || translate('Group #{id}'),
    // tslint:disable-next-line: binary-expression-operand-order
    DELETE_GROUP_TITLE: 'Delete group #{id}' || translate('Delete group #{id}'),
    // tslint:disable-next-line: binary-expression-operand-order
    DELETE_GROUP_MESSAGE: 'Do you really want to delete group?' || translate('Do you really want to delete group?'),
};

```

**Comment by shaharkazaz** [comment]
@EndyKaufman I think there is a combination of misuse and misunderstanding of the functionality. 
Just to clarify: 
- The keys extractor extract **keys**, so if you are not using any translation method on this value why do you need it as a key in your JSON? 
- The marker is used for marking translations in comments, meaning we will reach for the provided marker in comments and extract the keys from there.

You can achieve what you are looking for without the extra code as following:
```
// you must have some import from the transloco lib, otherwise, this file is skipped.
import { translate } from '@ngneat/transloco';

/* t('Username', 'Password') */
class SignInDto {
    static titles = {
        username: 'Username',
        password: 'Password',
    };
    username: string;
    password: string;
}
```

**Comment by EndyKaufman** [comment]
hello, see great examples, duplicate text turns out a lot, I use TC files with constants for the mobile application and for the backend and frontend

**Comment by shaharkazaz** [comment]
@EndyKaufman so if they are constant strings that aren't translated, why do you need them extracted into your JSON?

**Comment by EndyKaufman** [comment]
my old project use ngx-translate and https://github.com/biesbjerg/ngx-translate-extract#marker-function and share models for mobile application and for frontend
model: https://github.com/rucken/core/blob/develop/libs/rucken/core/src/lib/models/group.ts
translated file: https://github.com/rucken/core/blob/develop/libs/rucken/core/src/i18n/ru.i18n.ts
frontend form: https://github.com/rucken/core/blob/develop/libs/rucken/web/src/lib/entities/groups/group-modal/group-modal.component.html
mobile form: https://github.com/rucken/ionic/blob/develop/libs/rucken/ionic/src/lib/entities/groups/group-modal/group-modal.component.html

now i create new version and use a most popular library for it, and try change ngx-translate to transloco

**Comment by shaharkazaz** [comment]
Ok, and why are you not using the actual transloco `translate` function instead of the one imported from `import { translate } from '../utils/translate';`?

I still can't understand your use case.

**Comment by EndyKaufman** [comment]
translate used in my examples end marked functions from ngx-translate-extract need only for mark, it is dummy method 
https://github.com/rucken/core/blob/develop/libs/rucken/core/src/lib/utils/translate.ts
https://github.com/biesbjerg/ngx-translate-extract-marker/blob/master/projects/ngx-translate-extract-marker/src/lib/ngx-translate-extract-marker.ts

but you translate function is not marker, and when apply function, it is change value when it not need
https://github.com/ngneat/transloco/blob/master/projects/ngneat/transloco/src/lib/transloco.service.ts#L35

example:
```typescript
class GridWrapper {
displayedColumns = [translate('username')];
data=[{username:'alex'},{username:'bob'}];
}
```
and if try run in template
```
<ng-container *ngFor="let column of displayedColumns">
<ng-container *ngFor="let row of data">
{{row[column]}} <---- empty string 
</ng-container>
</ng-container>
```

for correct work I change ts code to:
```typescript
class GridWrapper {
displayedColumns = ['username'||translate('username')];
data=[{username:'alex'},{username:'bob'}];
}
```

**Comment by EndyKaufman** [comment]
it need for show title
```html
<table>
<tr>
<th *ngFor="let column of displayedColumns">
{{column|transloco}}
</th>
</tr>
<tr *ngFor="let row of data">
<td *ngFor="let column of displayedColumns">
{{row[column]}} <---- empty string 
</td>
</tr>
</table>
```

**Comment by EndyKaufman** [comment]
need new dummy method ```import { marker } from '@ngneat/transloco';```  only for extract strings without change it

**Comment by shaharkazaz** [comment]
@EndyKaufman You want the value for the object you are working with to be the key of the translation key which is then consumed somewhere in the app but also mark it for extraction for the keys manager?

**Comment by EndyKaufman** [comment]
yes, to use as one source of truth

**Comment by shaharkazaz** [comment]
@EndyKaufman currently we don't support such marker function since we didn't find a valid use case for working with a dev tool in production code.

You are welcome to open a PR for it 🙂

**Comment by EndyKaufman** [comment]
ok)

**Comment by EndyKaufman** [comment]
@shaharkazaz i create PR with this feature https://github.com/ngneat/transloco-keys-manager/pull/60
