### ISSUE TITLE
Cant install @ngneat/transloco:keys-manager via yarn package mananger

### ISSUE THREAD

**Issue by egel** [ngneat/transloco-keys-manager#63]
## I'm submitting a bug

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

in README there are installation instrudtions for `ng`, but the package name `@ngneat/transloco:keys-manager` with `:` is not working for yarn package manager

## Expected behavior

Adding a script on how to add it via `yarn` package manager. 

```
yarn global add @ngneat/transloco-keys-manager
```

## Minimal reproduction of the problem with instructions

1. following installation instruction and copying package name to yarn provide error
1. `yarn global add @ngneat/transloco:keys-manager`

    ```
    → yarn global add @ngneat/transloco:keys-manager
    yarn global v1.22.5
    [1/4] 🔍  Resolving packages...
    error An unexpected error occurred: "https://registry.yarnpkg.com/@ngneat%2ftransloco:keys-manager: Not found".
    info If you think this is a bug, please open a bug report with the information provided in 
    "/Users/maciejsypien/.config/yarn/global/yarn-error.log".
    info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
    ```

1. hen replacing `:` with `-` installation succeeded.

## What is the motivation / use case for changing the behavior?

trying/installing transloco-keys-manager CLI without a need to have angular project installed (via `ng`)

## Environment
 
For Tooling issues:
- Node version: v10.21.0
- Platform: MacOS 10.15.6 (19G2021)

## Keys manager config
None

**Comment by egel** [comment]
If the issue will be generally approved by authors, I can provide a proposition/solution pull request :)

**Comment by shaharkazaz** [comment]
@egel Thanks for suggesting a PR but I'll take this one and create a manual installation guide 🙂
