### ISSUE TITLE
Support for more than 65 characters for the key

### ISSUE THREAD

**Issue by Alegiter** [ngneat/transloco-keys-manager#65]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Extractor and finder cannot detect keys with more than 65 characters

## Expected behavior

More than 65 characters might be detected

## Minimal reproduction of the problem with instructions

In .html or .ts add key with more than 65 characters
Try to find or extract

## Environment

<pre><code>
Angular version: 10.0.2

 
For Tooling issues:
- Node version: 12/18/1  
- Platform:  Linux 
</code></pre>

## Keys manager config

```
module.exports = {
  rootTranslationsPath: 'src/assets/i18n/',
  langs: ['ru', 'en', 'kk', 'qq'],
  keysManager: {
    defaultValue: '{{key}}',
    replace: false,
    unflat: false,
    sort: true
  }
};
```

**Comment by Alegiter** [comment]
The problem is solved partially in .html with translocoRead directive

**Comment by shaharkazaz** [comment]
@Alegiter would be helpful if you can provide a small reproduction with the cases you encountered 🙂

**Comment by Alegiter** [comment]
My mistake :facepalm: 

Double-check my problem. And it was only in .html if I didn`t use translocoRead dirrective.
