### ISSUE TITLE
Scopes with hyphens in their name are not extracted correctly

### ISSUE THREAD

**Issue by uberpwner** [ngneat/transloco-keys-manager#66]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I have an app with lazy loaded modules. When adding transloco to those modules and naming scopes something like "public-module" `transloco-keys-manager extract` is extracting keys to main json file, not in subfolder. When I change scope name to something without hyphens, like "public" everything works as expected.
Also keys in component class, wrapped in `TranslocoService.translate('key', null, 'public-module')` end up in correct folder, but cannot be read by application. In browser console I see, that Transloco is loading this key from "publicModule".

## Expected behavior

I expect either this feature to work correctly with various scope names or to have documentation about scope naming.

## Minimal reproduction of the problem with instructions

I have created a repo with reproduction of this behaviour:
1. Clone https://github.com/uberpwner/transloco-key-manager-error
2. Run `yarn install`
3. Run `yarn run i18n:extract`
4. Observe contents of `assets/i18n` folder (part of lazy component keys are located in main json files
5. Change "lazy-module" to "lazy" in `lazy.module.ts`, `lazy.component.html` and `lazy.component.ts` and delete contents of `assets/i18n` folder
6. Run `yarn run i18n:extract`
7. Observe keys from lazy component located in correct subfolder under i18n

## Environment

<pre><code>
Angular version: 10.1.4
 
For Tooling issues:
- Node version: 14.9.0  
- Platform:  Windows 10

Others:
Package manager: Yarn v1.22.5
</code></pre>

## Keys manager config
<pre><code>
module.exports = {
	rootTranslationsPath: 'src/assets/i18n/',
	langs: ['en', 'ru'],
	defaultLang: 'en',
	keysManager: {
		defaultValue: '',
		unflat: true,
	},
};
</code></pre>

**Comment by shaharkazaz** [comment]
@uberpwner Thanks for providing a detailed issue with reproduction 🙂 Would you like to create a PR for it?

**Comment by uberpwner** [comment]
@shaharkazaz I'd like to, but I think I'll have time only next month. If it's okay - could you advice me on which parts of code should I look into?

**Comment by shaharkazaz** [comment]
@uberpwner I didn't try to debug it yet myself but I would look at `extractTsServiceKeys` & `buildKeysFromASTNodes` and try to understand what's going on in this scenario.

**Comment by shaharkazaz** [comment]
@uberpwner Do you still want to do it? 🙂

**Comment by uberpwner** [comment]
@shaharkazaz I'm very sorry! I completely forgot about this issue. Let me look into it and I'll write you back this wednesday.

**Comment by uberpwner** [comment]
@shaharkazaz I managed to find some time to look into this issue. Unfortunately it wasn't enougn to find its cause.
Since I'm still having trouble finding more free time and this issue is easily solved by removing hyphen from scope name (i.e. my-scope could be changed to myScope), I suggest closing this issue.

Sorry again for disappearing for a long time.

**Comment by shaharkazaz** [comment]
@uberpwner I had some time so I took a look at your use case.
I think you missed something regarding the scope name which led to misconfiguration, from the [scope's namespace](https://ngneat.github.io/transloco/docs/scope-configuration#scopes-namespace) section of the docs:

> By default, the namespace will be the scope name (camel cased), but we can override it by providing custom alias name in the module/component scope provider...

In the [reproduction you provided](https://github.com/uberpwner/transloco-key-manager-error) you have the following scope provider configuration:

```typescript
{ provide: TRANSLOCO_SCOPE, useValue: 'lazy-module' }
```

This means that when you want to refer to that scope you need to use `lazyModule` as the docs state.
If you wanted to refer to the scope as `lazy-module` you need to use the custom alias:

```typescript
{ provide: TRANSLOCO_SCOPE, useValue: {scope: 'lazy-module', alias: 'lazy-module' }}
```

Once I changed the provider the issue was resolved 🙂
