### ISSUE TITLE
Keys in templates with additional white spaces are not exported

### ISSUE THREAD

**Issue by foull** [ngneat/transloco-keys-manager#70]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Not sure if this is a designed behaviour or a bug. In my opinion, it's a bug :) 

I'm developing an Angular app which uses prettier to format code. I noticed that in some cases, prettier format the code with some additional white spaces which causes an issue with keys manager while extracting keys. Keys from templates are not exported properly. 

Firstly, I thought it's the same bug as described in https://github.com/ngneat/transloco-keys-manager/issues/65 -I'm not sure but it could be related.

## Expected behavior

All keys used in template should be exported to translation file.

## Minimal reproduction of the problem with instructions

```
{{ t("properly exported key") }}
{{
    t(
        "NOT exported key"
    )
}}
```

## Environment

<pre><code>
Angular version: 10.1.1

Browser: n/a
 
For Tooling issues:
- Node version: 12.18.3 
- Platform:  Mac 

Others:
@ngneat/transloco:  ^2.19.3
@ngneat/transloco-keys-manager: ^2.7.0

</code></pre>

## Keys manager config
```
{
        unflat: true,
        defaultValue: "{{keyWithoutScope}}",
}
```

**Comment by shaharkazaz** [comment]
@foull Can you verify it's working in v2.7.1?

**Comment by foull** [comment]
@shaharkazaz It's working good in v2.7.1. Thanks for a quick fix! :)
