### ISSUE TITLE
Support workspace.json as a config file

### ISSUE THREAD

**Issue by tatems** [ngneat/transloco-keys-manager#72]
### Is your feature request related to a problem? Please describe.
Nx has recently moved to use `workspace.json` as the main config file for new projects, instead of `angular.json`. It would be helpful to support specifying the config file name.

### Describe the solution you'd like
Allow a project to specify a `workspaceConfigFile`  field in the Transloco config file. The key manager would then look for that file instead of the default `angular.json` or `.angular.json`.

### Describe alternatives you've considered
For now, you can rename `workspace.json` back to `angular.json`, but that may not be guaranteed forever.

### Current behavior
After creating a new Nx project/updating an existing one to match the new pattern, the key manager fails to find the config file, and defaults to `src` as the project base path.

### Expected behavior
If a user specifies a config file path, the key manager loads the file instead of `angular.json` and runs as normal.

### Contribution
I want to make a pull request for this feature:
[x] Yes! 🚀
[ ] Maybe next time

**Comment by steflen** [comment]
pls merge
