### ISSUE TITLE
Bug does not work in components with inline loaders

### ISSUE THREAD

**Issue by heddendorp** [ngneat/transloco-keys-manager#74]
### Current behavior
I'm using an inline loader to load translation files for my lazy module and then selectTranslate to translate some strings in my component. The keys manager can not extract my keys.

### Expected behavior
I expect the key extractor to properly extract keys and recognize the scope I want to use

### Steps To Reproduce
Create a lazy module with an inline loader and a component.
Try to translate something inside the component.

`.selectTranslate()` only works if I inject the scope into the component and pass it on so it knows about the loader. The key manager only works if I put the scope as a string. Then however the translation is not loaded anymore.

### Keys manager config

```js
module.exports = {
  langs: ['en', 'de'],
  scopePathMap: {
    signup: 'src/app/modules/signup/i18n',
  },
};
```

### Environment
<pre><code>- Keys manager version: ^2.7.1
- Node version: v12.19.1
- Platform:  windows
</code></pre>

### Debug logs

irrelevant

### Contribution
I would like to make a pull request for this feature:
[ ] Yes! 🚀
[ ] Maybe next time

**Comment by ChazUK** [comment]
You can Inject the scope inside your component code. Try this

```
import { TranslocoService. TRANSLOCO_SCOPE } from '@ngneat/transloco';
...

constructor(
  ...
  private readonly translocoService: TranslocoService,
  @Inject(TRANSLOCO_SCOPE) private scope
  ) {}
  
  ngOnInit() {
    this.translocoService.selectTranslate(`${this.scope.scope}.key`)
      .subscribe(value => console.log(value));
  }
```

**Comment by shaharkazaz** [comment]
@heddendorp Can you please share a reproduction?

**Comment by shaharkazaz** [comment]
@heddendorp I suggest you update to the latest version and see if the issue persists.
If it does, please feel free to reopen once reproduction is provided 🙂
