### ISSUE TITLE
Feature: Default Language to use for missing keys / Adding a new language

### ISSUE THREAD

**Issue by ChazUK** [ngneat/transloco-keys-manager#77]
I've been looking at easy ways to add a new language and generating the required files across my project.

Currently my `transloco.config.js` file looks like this with a list of the scoped inline loaders for each component.

```javascript
module.exports = {
  langs: ['en', 'de'],
  keysManager: {
    sort: true,
  },
  scopePathMap: {
    backToTop: 'libs/ui/src/lib/atoms/back-to-top/i18n',
    downloadButton: 'libs/ui/src/lib/atoms/download-button/i18n',
    filterBy: 'libs/ui/src/lib/atoms/filter-pill/i18n',
    graphHeader: 'libs/ui/src/lib/atoms/graph-header/i18n',
    productCard: 'libs/ui/src/lib/atoms/product-card/i18n',
    skipLink: 'libs/ui/src/lib/atoms/skip-link/i18n',
    statusTag: 'libs/ui/src/lib/atoms/status-tag/i18n',
  },
};
```

I then added `it` to the langs array and ran `transloco-keys-manager extract --project ui` which I thought would re-run the extract process, not change `en` and `de` translation files, but then create new `it.json` files that contained either `Missing value for '...'"` or the already existing English value.

Unfortunately the German value is put in its place. Would it be possible for the config to contain a defaultLang, or take the first in the array as the default?

**Comment by rhuitl** [comment]
I think this is a bug introduced in 268644d45bb35e4b34d5a40b76a3e311c3fccbe9. The `mergeDeep()` method modifies the first parameter, so all previously processed languages will leak into the subsequent ones.
