### ISSUE TITLE
Support yarn when installing via schematics

### ISSUE THREAD

**Issue by openscript** [ngneat/transloco-keys-manager#84]
### Is your feature request related to a problem? Please describe.
Currently npm is used to install the keys manager. If the existing Angular project uses yarn it will take quite a while (depending on the devs machine up to a few minutes) and create a `package-lock.json` which is "redundant" with the `yarn.lock`.

### Describe the solution you'd like
The provided schematics should detect if yarn is used in the to be integrated Angular project and use it instead of npm.

### Describe alternatives you've considered
-

### Current behavior
The schematics always use npm to install.

### Expected behavior
The schematics use the projects package manager to install.

### Additional context
Angular project with yarn.

### Contribution
I want to make a pull request for this feature:
[ 🐣 ] Yes! 🚀
[ ] Maybe next time

If the owners of this projects are happy with this change, I will contribute this.

**Comment by shaharkazaz** [comment]
@openscript sounds good to me, waiting for that PR! 🙂

**Comment by openscript** [comment]
Interestingly this is already implemented: https://github.com/ngneat/transloco/blob/ac7fb139ad19fe52e2e987851bfd33a3554419a4/schematics/src/keys-manager/index.ts#L12

I have to investigate now, why this happened in my project...

**Comment by MickL** [comment]
This also broke my app. After install of transloco I got weird errors because partially npm was used. I fixed that by removing package-lock.json and deleting node_modules folder.

**Comment by shaharkazaz** [comment]
@openscript Please feel free to share the results here 🙂
